name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Builds the project (creates dist folder)

  deploy:
    name: Deploy to GitHub Pages
    needs: build  # Ensure the build job runs before deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run this job if the push is to main

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify the Node.js version you're using

      - name: Install dependencies
        run: npm install  # Install the required dependencies again for deployment

      - name: Deploy to GitHub Pages
        run: npm run deploy  # Run the deploy script which uses gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
